import {useEffect,useState} from "react";
import {FolderOpen,Download,FileText,Upload} from "lucide-react";
import api from "../services/api"; import PageHeader from "../components/PageHeader"; import Modal from "../components/Modal"; import Toast from "../components/Toast"; import Badge from "../components/Badge";
export default function Documents(){const[employees,setEmployees]=useState([]),[selected,setSelected]=useState(""),[docs,setDocs]=useState([]),[open,setOpen]=useState(false),[toast,setToast]=useState("");
 useEffect(()=>{api.get("/employees",{params:{limit:100}}).then(r=>setEmployees(r.data.items))},[]);
 useEffect(()=>{if(selected)api.get(`/employees/${selected}/documents`).then(r=>setDocs(r.data));else setDocs([])},[selected]);
 const upload=async e=>{e.preventDefault();const fd=new FormData(e.target);await api.post(`/employees/${selected}/documents`,fd,{headers:{"Content-Type":"multipart/form-data"}});setOpen(false);setToast("Document uploaded");api.get(`/employees/${selected}/documents`).then(r=>setDocs(r.data))};
 const base=import.meta.env.VITE_API_URL?.replace("/api","")||"http://localhost:5000";
 return <><PageHeader eyebrow="RECORDS" title="Documents" subtitle="Keep employee documents organized and easy to retrieve." action={<button className="primary-btn" disabled={!selected} onClick={()=>setOpen(true)}><Upload size={16}/> Upload document</button>}/>
 <div className="salary-selector panel"><FolderOpen size={20}/><div><span>Select employee</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose an employee…</option>{employees.map(e=><option key={e._id} value={e._id}>{e.fullName} · {e.employeeId}</option>)}</select></div></div>
 <div className="panel"><div className="panel-head"><div><h3>Employee documents</h3><p>{docs.length} documents</p></div></div>{docs.length?<div className="doc-list large">{docs.map(d=><div className="doc-item" key={d._id}><div className="doc-icon"><FileText/></div><div><b>{d.documentName}</b><small>{d.documentType} · {d.fileName}</small></div><div className="doc-actions"><Badge>{d.status}</Badge><a href={`${base}/${d.filePath?.replaceAll("\\","/")}`} target="_blank"><Download size={17}/></a></div></div>)}</div>:<div className="small-empty">Select an employee to view their documents.</div>}</div>
 <Modal open={open} onClose={()=>setOpen(false)} title="Upload document"><form className="form-grid" onSubmit={upload}><label>Document name<input name="documentName" required placeholder="Offer letter"/></label><label>Document type<select name="documentType">{["Offer Letter","Joining Letter","Experience Certificate","Relieving Letter","Salary Slip","ID Proof","Address Proof","Educational Certificate","Other"].map(x=><option key={x}>{x}</option>)}</select></label><label className="form-span file-input">Select file<input name="file" type="file" required/></label><div className="form-actions form-span"><button type="button" className="secondary-btn" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-btn">Upload</button></div></form></Modal><Toast message={toast} onClose={()=>setToast("")}/></>;
}
