import {useEffect,useState} from "react";
import {Plus,Search,Pencil,Trash2,UserRoundCheck} from "lucide-react";
import api from "../services/api";
import PageHeader from "../components/PageHeader"; import Modal from "../components/Modal"; import Badge from "../components/Badge"; import Toast from "../components/Toast"; import EmptyState from "../components/EmptyState";
const blank={internId:"",name:"",email:"",phone:"",college:"",course:"",department:"Technology",internshipRole:"Intern",startDate:new Date().toISOString().slice(0,10),endDate:"",mentor:"",stipend:5000,status:"Upcoming",remarks:""};
export default function Interns(){
 const [items,setItems]=useState([]),[q,setQ]=useState(""),[modal,setModal]=useState(false),[edit,setEdit]=useState(null),[toast,setToast]=useState("");
 const load=()=>api.get("/interns",{params:{search:q}}).then(r=>setItems(r.data));useEffect(()=>{load()},[q]);
 const save=async e=>{e.preventDefault();const f=new FormData(e.target),body=Object.fromEntries(f.entries());try{if(edit)await api.put(`/interns/${edit._id}`,body);else await api.post("/interns",body);setModal(false);setToast(edit?"Intern updated":"Intern added");load()}catch(err){setToast(err.response?.data?.message||"Could not save")}};
 const convert=async i=>{if(!confirm("Convert this intern to a full-time employee?"))return;await api.post(`/interns/${i._id}/convert`);setToast("Intern converted to employee");load()};
 const del=async id=>{if(confirm("Delete this intern?")){await api.delete(`/interns/${id}`);setToast("Intern deleted");load()}};
 return <><PageHeader eyebrow="PEOPLE" title="Interns" subtitle="Track internship journeys and convert high-potential interns into employees." action={<button className="primary-btn" onClick={()=>{setEdit(null);setModal(true)}}><Plus size={17}/> Add intern</button>}/>
 <div className="toolbar panel"><div className="search-box"><Search size={17}/><input placeholder="Search intern, ID or email…" value={q} onChange={e=>setQ(e.target.value)}/></div></div>
 <div className="panel table-panel"><div className="panel-head"><div><h3>Intern directory</h3><p>{items.length} interns</p></div></div>{items.length?<div className="table-wrap"><table><thead><tr><th>Intern</th><th>College</th><th>Role</th><th>Period</th><th>Stipend</th><th>Status</th><th></th></tr></thead><tbody>{items.map(i=><tr key={i._id}><td><div className="person"><div className="table-avatar">{i.name?.[0]}</div><div><b>{i.name}</b><small>{i.internId} · {i.email}</small></div></div></td><td>{i.college||"—"}</td><td>{i.internshipRole}</td><td>{i.startDate?new Date(i.startDate).toLocaleDateString("en-IN"):"—"} → {i.endDate?new Date(i.endDate).toLocaleDateString("en-IN"):"—"}</td><td>₹{Number(i.stipend||0).toLocaleString("en-IN")}</td><td><Badge>{i.status}</Badge></td><td><div className="row-actions"><button title="Convert" onClick={()=>convert(i)}><UserRoundCheck size={16}/></button><button onClick={()=>{setEdit(i);setModal(true)}}><Pencil size={16}/></button><button className="danger-icon" onClick={()=>del(i._id)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>:<EmptyState title="No interns yet"/>}</div>
 <Modal open={modal} onClose={()=>setModal(false)} title={edit?"Edit intern":"Add intern"} wide><form className="form-grid" onSubmit={save}>{Object.entries({...blank,...edit}).filter(([k])=>!["_id","createdAt","updatedAt","__v"].includes(k)).map(([k,v])=><label key={k}>{k.replace(/([A-Z])/g," $1")} *{["startDate","endDate"].includes(k)?<input name={k} type="date" defaultValue={v?.slice?.(0,10)||""}/>:k==="status"?<select name={k} defaultValue={v}>{["Upcoming","Active","Completed","Terminated"].map(x=><option key={x}>{x}</option>)}</select>:k==="stipend"?<input name={k} type="number" defaultValue={v}/>:<input name={k} defaultValue={v||""}/>}</label>)}<div className="form-actions form-span"><button type="button" className="secondary-btn" onClick={()=>setModal(false)}>Cancel</button><button className="primary-btn">Save intern</button></div></form></Modal><Toast message={toast} onClose={()=>setToast("")}/></>;
}
