import {useEffect,useState} from "react";
import {Building2,BriefcaseBusiness,Plus,Pencil,Trash2} from "lucide-react";
import api from "../services/api"; import PageHeader from "../components/PageHeader"; import Modal from "../components/Modal"; import Toast from "../components/Toast";
export default function Masters(){const[tab,setTab]=useState("departments"),[items,setItems]=useState([]),[open,setOpen]=useState(false),[edit,setEdit]=useState(null),[toast,setToast]=useState("");
 const load=()=>api.get(`/${tab}`).then(r=>setItems(r.data));useEffect(load,[tab]);
 const save=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));if(edit)await api.put(`/${tab}/${edit._id}`,body);else await api.post(`/${tab}`,body);setOpen(false);setToast(edit?"Updated":"Created");load()};
 const del=async id=>{if(confirm("Delete this master record?")){await api.delete(`/${tab}/${id}`);setToast("Deleted");load()}};
 return <><PageHeader eyebrow="CONFIGURATION" title="Departments & designations" subtitle="Manage master data used across employee records." action={<button className="primary-btn" onClick={()=>{setEdit(null);setOpen(true)}}><Plus size={17}/> Add {tab==="departments"?"department":"designation"}</button>}/>
 <div className="tabs panel"><button className={tab==="departments"?"active":""} onClick={()=>setTab("departments")}><Building2 size={16}/> Departments</button><button className={tab==="designations"?"active":""} onClick={()=>setTab("designations")}><BriefcaseBusiness size={16}/> Designations</button></div>
 <div className="master-grid">{items.map(i=><div className="master-card panel" key={i._id}><div className="master-icon">{tab==="departments"?<Building2/>:<BriefcaseBusiness/>}</div><div><h3>{i.name}</h3><p>{i.description||i.department||"Organization master data"}</p></div><div className="row-actions"><button onClick={()=>{setEdit(i);setOpen(true)}}><Pencil size={16}/></button><button className="danger-icon" onClick={()=>del(i._id)}><Trash2 size={16}/></button></div></div>)}</div>
 <Modal open={open} onClose={()=>setOpen(false)} title={edit?"Edit record":`Add ${tab==="departments"?"department":"designation"}`}><form className="form-grid" onSubmit={save}><label className="form-span">Name<input name="name" required defaultValue={edit?.name||""}/></label>{tab==="departments"?<label className="form-span">Description<input name="description" defaultValue={edit?.description||""}/></label>:<label className="form-span">Department<input name="department" defaultValue={edit?.department||""}/></label>}<div className="form-actions form-span"><button type="button" className="secondary-btn" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-btn">Save</button></div></form></Modal><Toast message={toast} onClose={()=>setToast("")}/></>;
}
