import {useEffect,useState} from "react";
import {Plus,Download,FileText,Pencil} from "lucide-react";
import api from "../services/api"; import PageHeader from "../components/PageHeader"; import Modal from "../components/Modal"; import Badge from "../components/Badge"; import Toast from "../components/Toast";
const blank={candidateName:"",designation:"Software Developer",department:"Technology",joiningDate:"",employmentType:"Full-time",salaryCTC:0,probationPeriod:3,workLocation:"Noida",reportingManager:"",offerDate:new Date().toISOString().slice(0,10),status:"Draft"};
export default function Offers(){const[items,setItems]=useState([]),[employees,setEmployees]=useState([]),[open,setOpen]=useState(false),[toast,setToast]=useState("");
 const load=()=>api.get("/offers").then(r=>setItems(r.data));useEffect(()=>{load();api.get("/employees",{params:{limit:100}}).then(r=>setEmployees(r.data.items))},[]);
 const save=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));await api.post("/offers",body);setOpen(false);setToast("Offer created");load()};
 const pdf=id=>{const token=localStorage.getItem("scorecare_token");fetch(`${import.meta.env.VITE_API_URL||"http://localhost:5000/api"}/offers/${id}/pdf`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.blob()).then(b=>{const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="offer-letter.pdf";a.click()})};
 return <><PageHeader eyebrow="EMPLOYMENT" title="Offer letters" subtitle="Create, track and download professional offer letters." action={<button className="primary-btn" onClick={()=>setOpen(true)}><Plus size={17}/> Create offer</button>}/><div className="panel table-panel"><div className="panel-head"><div><h3>Offer history</h3><p>{items.length} offers</p></div></div><div className="table-wrap"><table><thead><tr><th>Candidate</th><th>Role</th><th>Joining</th><th>CTC</th><th>Offer date</th><th>Status</th><th></th></tr></thead><tbody>{items.map(o=><tr key={o._id}><td><div className="person"><div className="doc-icon"><FileText size={17}/></div><div><b>{o.candidateName}</b><small>{o.employee?.employeeId||"Candidate"}</small></div></div></td><td>{o.designation}</td><td>{o.joiningDate?new Date(o.joiningDate).toLocaleDateString("en-IN"):"—"}</td><td>₹{Number(o.salaryCTC||0).toLocaleString("en-IN")}</td><td>{new Date(o.offerDate).toLocaleDateString("en-IN")}</td><td><Badge>{o.status}</Badge></td><td><div className="row-actions"><button onClick={()=>pdf(o._id)}><Download size={16}/></button></div></td></tr>)}</tbody></table></div></div>
 <Modal open={open} onClose={()=>setOpen(false)} title="Create offer letter" wide><form className="form-grid" onSubmit={save}><label>Existing employee<select name="employee" defaultValue=""><option value="">Candidate / new hire</option>{employees.map(e=><option key={e._id} value={e._id}>{e.fullName} · {e.employeeId}</option>)}</select></label><label>Candidate name<input name="candidateName" required/></label><label>Designation<input name="designation" defaultValue={blank.designation}/></label><label>Department<input name="department" defaultValue={blank.department}/></label><label>Joining date<input name="joiningDate" type="date"/></label><label>Employment type<select name="employmentType"><option>Full-time</option><option>Part-time</option><option>Contract</option></select></label><label>Annual CTC<input name="salaryCTC" type="number"/></label><label>Probation (months)<input name="probationPeriod" type="number" defaultValue="3"/></label><label>Work location<input name="workLocation" defaultValue="Noida"/></label><label>Reporting manager<input name="reportingManager"/></label><label>Offer date<input name="offerDate" type="date" defaultValue={blank.offerDate}/></label><label>Status<select name="status">{["Draft","Generated","Sent","Accepted","Rejected"].map(x=><option key={x}>{x}</option>)}</select></label><div className="form-actions form-span"><button type="button" className="secondary-btn" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-btn">Create offer</button></div></form></Modal><Toast message={toast} onClose={()=>setToast("")}/></>;
}
