import {useEffect,useState} from "react";
import {WalletCards,Plus,Download} from "lucide-react";
import api from "../services/api"; import PageHeader from "../components/PageHeader"; import Modal from "../components/Modal"; import Toast from "../components/Toast"; import Badge from "../components/Badge";
export default function Salary(){const[employees,setEmployees]=useState([]),[selected,setSelected]=useState(""),[history,setHistory]=useState([]),[open,setOpen]=useState(false),[slip,setSlip]=useState(false),[toast,setToast]=useState("");
 useEffect(()=>{api.get("/employees",{params:{limit:100}}).then(r=>setEmployees(r.data.items))},[]);
 useEffect(()=>{if(selected)api.get(`/employees/${selected}/salary`).then(r=>setHistory(r.data))},[selected]);
 const save=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));await api.post(`/employees/${selected}/salary`,body);setOpen(false);setToast("Salary revision saved");api.get(`/employees/${selected}/salary`).then(r=>setHistory(r.data))};
 const saveSlip=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.employee=selected;const r=await api.post("/salary-slips",body);setSlip(false);setToast("Salary slip generated");download(r.data._id)};
 const download=id=>{const token=localStorage.getItem("scorecare_token");fetch(`${import.meta.env.VITE_API_URL||"http://localhost:5000/api"}/salary-slips/${id}/pdf`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.blob()).then(b=>{const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="salary-slip.pdf";a.click()})};
 return <><PageHeader eyebrow="PAYROLL" title="Salary management" subtitle="Maintain compensation, revisions and monthly salary slips." action={<div className="header-actions"><button className="secondary-btn" disabled={!selected} onClick={()=>setSlip(true)}><Download size={16}/> Generate slip</button><button className="primary-btn" disabled={!selected} onClick={()=>setOpen(true)}><Plus size={16}/> Add revision</button></div>}/>
 <div className="salary-selector panel"><WalletCards size={20}/><div><span>Select employee</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose an employee…</option>{employees.map(e=><option key={e._id} value={e._id}>{e.fullName} · {e.employeeId}</option>)}</select></div></div>
 <div className="panel table-panel"><div className="panel-head"><div><h3>Salary history</h3><p>{selected?"All compensation revisions for selected employee":"Select an employee to view salary history"}</p></div></div>{history.length?<div className="table-wrap"><table><thead><tr><th>Effective date</th><th>Basic</th><th>HRA</th><th>Allowances</th><th>Deductions</th><th>Net salary</th><th>CTC</th></tr></thead><tbody>{history.map(s=><tr key={s._id}><td>{new Date(s.effectiveFrom).toLocaleDateString("en-IN")}</td><td>₹{Number(s.basicSalary).toLocaleString("en-IN")}</td><td>₹{Number(s.hra).toLocaleString("en-IN")}</td><td>₹{Number(s.allowances).toLocaleString("en-IN")}</td><td>₹{Number(s.deductions).toLocaleString("en-IN")}</td><td><b>₹{Number(s.netSalary).toLocaleString("en-IN")}</b></td><td><Badge>₹{Number(s.ctc).toLocaleString("en-IN")}</Badge></td></tr>)}</tbody></table></div>:<div className="small-empty">No salary records for this employee.</div>}</div>
 <Modal open={open} onClose={()=>setOpen(false)} title="Add salary revision"><SalaryForm onSubmit={save}/></Modal><Modal open={slip} onClose={()=>setSlip(false)} title="Generate salary slip"><form className="form-grid" onSubmit={saveSlip}><label>Month<select name="month" defaultValue={new Date().getMonth()+1}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2000,i,1).toLocaleString("en-IN",{month:"long"})}</option>)}</select></label><label>Year<input name="year" type="number" defaultValue={new Date().getFullYear()}/></label><label>Basic salary<input name="basicSalary" type="number" required/></label><label>Allowances<input name="allowances" type="number"/></label><label>Deductions<input name="deductions" type="number"/></label><label>Bonus<input name="bonus" type="number"/></label><div className="form-actions form-span"><button type="button" className="secondary-btn" onClick={()=>setSlip(false)}>Cancel</button><button className="primary-btn">Generate PDF</button></div></form></Modal><Toast message={toast} onClose={()=>setToast("")}/></>;
}
function SalaryForm({onSubmit}){return <form className="form-grid" onSubmit={onSubmit}><label>Basic salary<input name="basicSalary" type="number" required/></label><label>HRA<input name="hra" type="number"/></label><label>Allowances<input name="allowances" type="number"/></label><label>Deductions<input name="deductions" type="number"/></label><label>Bonus<input name="bonus" type="number"/></label><label>CTC<input name="ctc" type="number" required/></label><label>Effective from<input name="effectiveFrom" type="date" required/></label><label>Revision date<input name="salaryRevisionDate" type="date"/></label><label className="form-span">Reason<input name="reason" placeholder="Annual revision"/></label><div className="form-actions form-span"><button type="button" className="secondary-btn">Cancel</button><button className="primary-btn">Save revision</button></div></form>}
